version: "3"

services:
  postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres

  pact_broker:
    image: dius/pact_broker
    build: .
    ports:
      - "80:80"
    depends_on:
      - postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: pactbrokeruser
      PACT_BROKER_DATABASE_PASSWORD: 1234
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: pactbroker
      PACT_BROKER_PORT: "80"

volumes:
  postgres-volume: